<?php

declare(strict_types=1);

$constants = [
    'LF' => LF,
    'CR' => CR,
    'CRLF' => CRLF,

    'FILE_DENY_PATTERN_DEFAULT' => FILE_DENY_PATTERN_DEFAULT,

    'TYPO3_REQUESTTYPE' => TYPO3_REQUESTTYPE,
    'TYPO3_REQUESTTYPE_FE' => TYPO3_REQUESTTYPE_FE,
    'TYPO3_REQUESTTYPE_BE' => TYPO3_REQUESTTYPE_BE,
    'TYPO3_REQUESTTYPE_CLI' => TYPO3_REQUESTTYPE_CLI,
    'TYPO3_REQUESTTYPE_AJAX' => TYPO3_REQUESTTYPE_AJAX,
    'TYPO3_REQUESTTYPE_INSTALL' => TYPO3_REQUESTTYPE_INSTALL,

    'TYPO3_MODE' => TYPO3_MODE,
    'TYPO3_mainDir' => TYPO3_mainDir,
    'TYPO3_version' => TYPO3_version,
    'TYPO3_branch' => TYPO3_branch,
];
